# Generated by Django 5.0.6 on 2024-06-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph1',
            name='cr',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='graph1',
            name='inst',
            field=models.CharField(max_length=255),
        ),
    ]
