# Generated by Django 5.0.6 on 2024-06-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decode', '0002_alter_graph1_cr_alter_graph1_inst'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph1',
            name='branch',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
