# Generated by Django 5.0.6 on 2024-06-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decode', '0003_graph1_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph1',
            name='seat_type',
            field=models.CharField(default='open', max_length=50),
        ),
        migrations.AlterField(
            model_name='graph1',
            name='branch',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='graph1',
            name='inst',
            field=models.CharField(max_length=200),
        ),
    ]
