# Generated by Django 5.0.6 on 2024-06-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decode', '0004_graph1_seat_type_alter_graph1_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph1',
            name='seat_type',
            field=models.CharField(max_length=50),
        ),
    ]
