# Generated by Django 5.0.6 on 2024-06-11 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decode', '0005_alter_graph1_seat_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph1',
            name='seat_type',
        ),
    ]
