# Generated by Django 5.0.6 on 2024-06-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decode', '0007_graph1_seat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph1',
            name='seat_type',
            field=models.CharField(max_length=50),
        ),
    ]
