# Generated by Django 5.0.6 on 2024-06-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decode', '0009_remove_graph1_seat_type_graph1_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph1',
            name='seat',
            field=models.CharField(max_length=200),
        ),
    ]
