# Generated by Django 5.0.6 on 2024-06-11 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decode', '0010_alter_graph1_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph1',
            name='seat',
        ),
    ]
