# Generated by Django 5.0.6 on 2024-06-15 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decode', '0011_remove_graph1_seat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Graph1',
        ),
    ]
